from sudoku_solver import State
from sudoku_solver import bfs

s0 = State(3)
s0.sudoku.tablero.agregar_valor(5,0,0)
s0.sudoku.tablero.agregar_valor(3,0,1)
s0.sudoku.tablero.agregar_valor(7,0,4)
s0.sudoku.tablero.agregar_valor(6,1,0)
s0.sudoku.tablero.agregar_valor(1,1,3)
s0.sudoku.tablero.agregar_valor(9,1,4)
s0.sudoku.tablero.agregar_valor(5,1,5)
s0.sudoku.tablero.agregar_valor(9,2,1)
s0.sudoku.tablero.agregar_valor(8,2,2)
s0.sudoku.tablero.agregar_valor(6,2,7)
s0.sudoku.tablero.agregar_valor(8,3,0)
s0.sudoku.tablero.agregar_valor(6,3,4)
s0.sudoku.tablero.agregar_valor(3,3,8)
s0.sudoku.tablero.agregar_valor(4,4,0)
s0.sudoku.tablero.agregar_valor(8,4,3)
s0.sudoku.tablero.agregar_valor(3,4,5)
s0.sudoku.tablero.agregar_valor(1,4,8)
s0.sudoku.tablero.agregar_valor(7,5,0)
s0.sudoku.tablero.agregar_valor(2,5,4)
s0.sudoku.tablero.agregar_valor(6,5,8)
s0.sudoku.tablero.agregar_valor(6,6,1)
s0.sudoku.tablero.agregar_valor(2,6,6)
s0.sudoku.tablero.agregar_valor(8,6,7)
s0.sudoku.tablero.agregar_valor(4,7,3)
s0.sudoku.tablero.agregar_valor(1,7,4)
s0.sudoku.tablero.agregar_valor(9,7,5)
s0.sudoku.tablero.agregar_valor(5,7,8)
s0.sudoku.tablero.agregar_valor(8,8,4)
s0.sudoku.tablero.agregar_valor(7,8,7)
s0.sudoku.tablero.agregar_valor(9,8,8)
print(s0.sudoku.tablero.retorna_matriz())

sFinal = bfs(s0)
print(sFinal)